// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA49zejkdl9DUQ5dh6rt983t9xfPdTFxlU',
    appId: '1:934788130436:web:82a04cdc90e195f43dc4d1',
    messagingSenderId: '934788130436',
    projectId: 'imiu-6b077',
    authDomain: 'imiu-6b077.firebaseapp.com',
    storageBucket: 'imiu-6b077.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRaGIbH1M025R_p1LaRRRT0A3wwTQe8is',
    appId: '1:934788130436:android:2f853b6ccc98132a3dc4d1',
    messagingSenderId: '934788130436',
    projectId: 'imiu-6b077',
    storageBucket: 'imiu-6b077.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcVPqtxCqBBYHYG6TFQWzhejcsDVVicIs',
    appId: '1:934788130436:ios:35991ee755b0ceb73dc4d1',
    messagingSenderId: '934788130436',
    projectId: 'imiu-6b077',
    storageBucket: 'imiu-6b077.appspot.com',
    iosClientId: '934788130436-skgnur71b1mrkk7dcr337smves0jv1pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.imiuMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcVPqtxCqBBYHYG6TFQWzhejcsDVVicIs',
    appId: '1:934788130436:ios:7b3cdc1a9bec1c8a3dc4d1',
    messagingSenderId: '934788130436',
    projectId: 'imiu-6b077',
    storageBucket: 'imiu-6b077.appspot.com',
    iosClientId: '934788130436-maf5iu2penosbcb4ft3m199unf8qvro4.apps.googleusercontent.com',
    iosBundleId: 'com.example.imiuMobile.RunnerTests',
  );
}
